# I do not wish to receive email notifications
notifications:
  email: false


# Use a custom build infrastructure
# See  https://github.com/hvr/multi-ghc-travis
language: c

# explicitly request container-based infrastructure
sudo: false

# build matrix
matrix:
  include:
    - env: CABALVER=1.16 GHCVER=7.6.3
      addons: {apt: {packages: [cabal-install-1.16,ghc-7.6.3],  sources: [hvr-ghc]}}
    - env: CABALVER=1.18 GHCVER=7.8.4
      addons: {apt: {packages: [cabal-install-1.18,ghc-7.8.4],  sources: [hvr-ghc]}}
    - env: CABALVER=1.22 GHCVER=7.10.1
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.1], sources: [hvr-ghc]}}
    - env: CABALVER=1.24 GHCVER=8.0.1
      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.1],  sources: [hvr-ghc]}}
    - env: CABALVER=2.2 GHCVER=8.2.2
      addons: {apt: {packages: [cabal-install-2.2,ghc-8.2.2],  sources: [hvr-ghc]}}
    - env: CABALVER=2.2 GHCVER=8.4.3
      addons: {apt: {packages: [cabal-install-2.2,ghc-8.4.3],  sources: [hvr-ghc]}}
#  allow_failures:
#    - env: CABALVER=1.24 GHCVER=8.0.1

# Note: the distinction between `before_install` and `install` is not important.
before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update
 - cd reactive-banana/
 - cabal install --only-dependencies --enable-tests --enable-benchmarks

before_script:
  - cabal configure
  - cabal sdist
  - cd ../..
  - tar -xf reactive-banana/reactive-banana/dist/reactive-banana*.tar.gz
  - cd reactive-banana-*
script:
  - cabal configure --enable-tests && cabal build && cabal test
