- ignore:
    name: Use const
- ignore:
    name: Evaluate
- ignore:
    name: Use newtype instead of data
- ignore:
    name: Avoid lambda
- ignore:
    name: Eta reduce
- ignore:
    name: Redundant lambda
- ignore:
    name: Avoid lambda using `infix`
